# Generated by Django 3.0.8 on 2021-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210430_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='category-png-9.png', upload_to='images'),
        ),
    ]
