# Generated by Django 3.1.7 on 2021-03-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F2812740%2Fadd_category_playlist_icon&psig=AOvVaw23PXBlHvNcIdb4iQycOA4F&ust=1616072938090000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIj2jv-yt-8CFQAAAAAdAAAAABAD', max_length=200),
        ),
    ]
