# Generated by Django 3.1.7 on 2021-03-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210317_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category-png-9.png', upload_to='images'),
        ),
    ]
