# Generated by Django 3.1.7 on 2021-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210317_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='https://www.sitepronews.com/wp-content/uploads/2014/02/logo-icon.png', max_length=500),
        ),
    ]
