# Generated by Django 3.1.7 on 2021-03-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210317_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='category-png-9.png', upload_to='images'),
        ),
    ]
