# Generated by Django 3.1.7 on 2021-03-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
