# Generated by Django 3.1.7 on 2021-03-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210326_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
