# Generated by Django 3.1.7 on 2021-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210326_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
