# Generated by Django 3.1.7 on 2021-03-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_matts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='matts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.matts'),
        ),
    ]
