# Generated by Django 3.1.7 on 2021-03-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MattsPerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='matt',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.matts'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_product',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
        migrations.AddField(
            model_name='product',
            name='matt_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.mattsperproduct'),
        ),
    ]
