# Generated by Django 3.1.7 on 2021-03-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20210326_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='matt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.matts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='matt_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.mattsperproduct'),
        ),
    ]
