# Generated by Django 3.1.7 on 2021-04-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='matt_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_product',
        ),
        migrations.DeleteModel(
            name='MattsPerProduct',
        ),
    ]
