# Generated by Django 3.1.7 on 2021-04-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20210415_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='product',
        ),
        migrations.AddField(
            model_name='check',
            name='product',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
