# Generated by Django 3.0.8 on 2021-04-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20210415_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='matt',
            field=models.CharField(choices=[('KG', 'kg'), ('G', 'g'), ('Pakuotė', 'pakuotė')], max_length=20),
        ),
    ]
