# Generated by Django 3.0.8 on 2021-04-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20210418_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='product',
        ),
        migrations.RemoveField(
            model_name='check',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ProductInCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='products',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductInCheck'),
        ),
    ]
