# Generated by Django 3.0.8 on 2021-04-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20210418_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductInCheck'),
        ),
    ]
