# Generated by Django 3.0.8 on 2021-04-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210418_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='price_all',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productincheck',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='check',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductInCheck'),
        ),
    ]
