# Generated by Django 3.0.8 on 2021-04-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20210418_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
