# Generated by Django 3.0.8 on 2021-04-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_delete_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInCheck',
        ),
    ]
