# Generated by Django 3.0.8 on 2021-04-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_check_productincheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincheck',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
