# Generated by Django 3.0.8 on 2021-04-18 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20210418_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Supplier'),
        ),
    ]
