# Generated by Django 3.0.8 on 2021-05-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincheck',
            name='product',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='ProductInCheck',
        ),
    ]
